# Common configuration shared between all applications
configserver:
  name: Juninho.com.br (Influenzer, Wok) Docker JHipster Registry Config Server
    status: Connected to the JHipster Registry config server, using https://git.juninho.com.br/mundo-do-codigo/jhipster-registry-a2config-config/-/edit/master/application.yml

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                base64-secret: ZTdiODkxMTVjOWFiMTEzYzI5YmQ3N2MzODljYjliYjc0NjkwNzg4ZDgxZDgxZWQzOTM5YzEzMmRjOWE4ZmYzNjAzNGNhN2M5OWE0YjU5N2I0NmI4YzFhZDUxZDUxMjU3MjA2NjY0Y2RiOGQwYjNjMGQ3OWEzNDhhNzdmNDQ1NjE=
spring:
  security:
    user:
      password: admin
eureka:
  client:
    service-url:
        defaultZone: http://admin:admin@registro.juninho.com.br:8761/eureka/
      #defaultZone: http://admin:a2portais@localhost:8761/eureka/

# Enable /management/logfile endpoint for all apps
logging:
    path: /dados/apps/jhipster-registry/log
    file: ${spring.application.name}.log
